name: flutly_store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  bloc_concurrency: ^0.3.0
  cloud_firestore: ^6.1.1
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.2
  fpdart: ^1.2.0
  get_it: ^9.0.5
  go_router: ^17.0.0
  infinite_scroll_pagination: ^5.1.1
  reactive_forms: ^18.2.0
  shared_preferences: ^2.5.3
  shimmer_animation: ^2.2.2
  step_progress: ^2.7.1
  stream_transform: ^2.1.1
  cached_network_image: ^3.4.1
  crypto: ^3.0.6
  easy_localization: ^3.0.8
  easy_localization_loader: ^2.0.2
  firebase_crashlytics: ^5.0.6
  firebase_analytics: ^12.1.0
  flutter_native_splash: ^2.4.7
  animations: ^2.1.1
  collection: ^1.19.1
  flutter_staggered_animations: ^1.1.1
  sliver_tools: ^0.2.12
  figma_squircle: ^0.6.3
  google_sign_in: ^7.2.0
  platform: ^3.1.6
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/splash/
    - assets/translations/en/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
